---
- hosts: backend
  sudo: yes
  roles:
    - role: base
    - role: webserver
      tags: ['apache', 'webserver']
      vhosts:
        - { hostname: 'ansible.local', dir: '/home/vagrant/ansible/htdocs' }
