---
- name: Install MySQL
  apt: pkg={{ item }} state=present
  notify: Restart MySQL
  with_items:
   - mysql-server
   - python-mysqldb

- name: Update MySQL root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ mysql_root_password }} priv=*.*:ALL,GRANT
  with_items:
   - "{{ ansible_hostname }}"
   - 127.0.0.1
   - ::1
   - localhost

- name: Copy .my.cnf file with root password credentials
  template: src=.my.cnf dest=/root/.my.cnf owner=root mode=0600

- name: Create example MySQL User
  mysql_user: >
    host={{ item.host }}
    name=example
    password={{ mysql_app_password }}
    priv=*.*:ALL state=present
    login_password={{ mysql_root_password }}
    login_user=root
  notify: Restart MySQL
  with_items:
    - { host: 'localhost' }

- name: Create example database
  mysql_db: >
    name=example
    state=present
    collation=utf8_general_ci
    encoding=utf8
    login_host=localhost
    login_user=root
    login_password={{ mysql_root_password }}
