---
- name: Install Apache
  tags: ['online']
  apt: pkg=apache2-mpm-prefork state=present

- name: Delete default Apache vhost
  file: path=/etc/apache2/sites-enabled/000-default state=absent
  notify: Restart Apache

- name: Generate Vhosts
  template:
    src=vhost.conf
    dest=/etc/apache2/sites-enabled/{{ item.hostname }}.conf
    owner=www-data
    group=www-data
    mode=0644
  with_items: vhosts
  notify: Restart Apache
